hosts:
  dev_ai:
    description: AI开发和测试服务器
    ip: 106.75.77.78
    name: AI-Dev
    password: xhLWGuzGbF6
    port: 9001
    tags:
    - dev
    - ai
    username: dev1
  prod_ai:
    description: AI服务生产环境
    ip: 106.75.77.78
    name: AI-Prod
    password: xhLWGuzGbF6
    port: 9001
    tags:
    - prod
    - ai
    username: dev1
